- wpf/Charts/Adornments/Label.md
Updated the code example, when we set LabelTemplate property need to set SegmentLabelContent property becomes LabelContentPath.
For more details, please refer the below link
https://support.syncfusion.com/agent/tickets/363768
> XAMARIN-33322-Update the chart datamarker label ug document

- wpf/TreeGrid/Export-To-Excel.md
- wpf/TreeGrid/Export-To-PDF.md
UWP-10502 Need to add the assembly requirement for Nuget in Export to PDF and Export to Excel in UWP and WPF
> UWP-10502 Need to add the assembly requirement for Nuget in Export to PDF and Export to Excel in UWP and WPF

- wpf/Charts/Interactive-Features/Tooltip.md
chart tooltip style code was changed
> WPF-59865-Resolved the chart tooltip code changes

- wpf/Surface-Chart/Surface-Area.md
- wpf/Surface-Chart/Surface-Axis.md
Update the property links properly in the table
> WPF-60667: Update the property links properly in the table

- wpf/Surface-Chart/Surface-Area.md
- wpf/Surface-Chart/Surface-Axis.md
> WPF-60667 : API reference link issue resolved in SurfaceChart Control.

- wpf/Surface-Chart/Surface-Area.md
API reference link issue is resolved in SurfaceChart.
> WPF-60667 : API reference link issue is resolved in SurfaceChart.

- wpf/Diagram/Swimlane/Lane/Lane.md
- wpf/Diagram/Swimlane/Phase.md
- wpf/Diagram/Swimlane/Swimlane.md
WPF-60640 Swimlane pages code snippets are validated and updated
> WPF-60640 Swimlane pages code snippets are validated and updated

- wpf/Classic/Schedule/Recurrence.md
- wpf/Classic/Schedule/appointments.md
- wpf/Classic/Schedule/timelineview.md
- wpf/Classic/Schedule/views.md
- wpf/Scheduler/Appointments.md
- wpf/Scheduler/Date-Navigations.md
- wpf/Scheduler/DaysView.md
- wpf/Scheduler/Month-View.md
- wpf/Scheduler/Resource-Grouping.md
- wpf/Scheduler/TimelineView.md
Updated UG review correction for SfScheduler and SfSchedule controls.
> WINUI-2356-[WPF]Updated UG review correction for SfScheduler and SfSchedule controls.

- wpf/Maps/Bubbles.md
- wpf/Maps/Shapes-Color-Customization.md
Link modifications for proper appearance in the table
> WPF-60785: Update the property links properly in the table

- wpf/Circular-ProgressBar/Getting-Started.md
Hi Team,
To include sample for Circular Progressbar control. Kindly review the changes and let me know your feedback.
With Regards,
Hemalatha D.
> WPF-60645 Need to include sample for Circular Progressbar

- wpf/Diagram/Node.md
WPF-60814 Boundary Constraints is added in UG
> WPF-60814 Boundary Constraints is added in UG

- wpf/MaskedTextBox/Input-Restriction.md
Hi @ChristoIssac,
Worked on Site Audit Image descriptions issues, merge these changes.
Regards,
Gowthaman
> SEO-2154_Site_Audit_Issues

- wpf/DataGrid/MVVM.md
Modified broken link in MVVM of DataGrid
> WF-62748 Modified broken link in mvvm of DataGrid

- wpf/Pdf-Viewer/Working-with-PDF-Layers.md
UG content to toggle layers from code behind
> WPF-53871 - Toggling Layers from code behind

- wpf/DataGrid/Rows.md
- wpf/TreeGrid/Rows.md
Worked on Bing report issues, merge these changes.
Regards,
Gowthaman
> SEO-2190_Site_Audit_Issues

- wpf/Navigation-Drawer/Keyboard-Support.md
Updated sample code for KeyboardSupport under SfNavigationDrawer
> WPF-61008: Updated Sample Code in Keyboard Support

- wpf/Navigation-Drawer/Keyboard-Support.md
Updated sample code for KeyboardSupport under SfNavigationDrawer
> WPF-61008: Added KeyboardSupport Sample Code in SfNavigationDrawer

- wpf/Diagram/Connector/SelectionAndDragging.md
- wpf/Diagram/Exporting.md
- wpf/Diagram/Interaction/Selection.md
- wpf/Diagram/Interaction/UserHandle.md
- wpf/Diagram/Node.md
- wpf/Diagram/Port/Port.md
- wpf/Diagram/Swimlane/Lane/Interaction.md
ImageSize, ImageShrunk properties of ExportSettings class APIs are explained in SfDiagram UG Exporting Page.
> WPF-50071 Need to add ImageSize and ImageShrunk, Clipping API's in exporting page

- wpf/CheckedListBox/Check-items.md
Hi @JeganRavichandran ,
I have changed the style of check list item from ItemContainerStyle to Resources. 
Regards,
Bagavathi Perumal A
> WPF-61148-Need to correct the codes in the CheckListBox UG documentation

- wpf/Menu/MenuItemSeparator-Support.md
**Issue in content**
Need to correct the code example for WPF MenuAdv control in UG documentation 
**Solution**
Adding the full code snippet and namespace to create/ add a MenuAdv control in view.
> WPF-58349 [UG]- Need to correct the code example for WPF MenuAdv control in UG documentation 

- wpf/Installation/Installation-errors.md
- wpf/Installation/offline-installer/how-to-download.md
- wpf/Installation/web-installer/how-to-download.md
- wpf/Licensing/how-to-generate.md
- wpf/Licensing/licensing-errors.md
- wpf/Licensing/licensing-faq/how-to-upgrade-from-trial-version-after-purchasing-a-license.md
- wpf/Licensing/licensing-faq/registering-syncfusion-account-for-nuget-org-user.md
- wpf/Licensing/overview.md
- wpf/Upgrade/how-to-upgrade.md
TOC Structure and link Changes
> IN-18125-UG-Documentation-wpf-hotfix

- wpf/Docking/Pattern-and-Practices.md
Code Changes to correct the casing in code snippets of the documentation
> WPF-61246-Change-sample-code-snippets-to-correct-cases

- wpf/Scheduler/Appointment-Editing.md
- wpf/Scheduler/Events.md
XAMARIN-43498-newly added feature is updated in WPF Scheduler is reviewed by @Chrispineagunja
> XAMARIN-43498-newly added feature is updated in WPF Scheduler

- wpf-toc.html
- Updated the toc for Text Callout and Squiggly annotation UG
> WPF-57891_3 Update toc for Text Callout and Squiggly annotation UG

- wpf/Classic/Chart/How-to/Auto-scale-Y-axis-when-X-axis-is-zoomed.md
- wpf/Syntax-Editor/Basic-Editing/Find-and-Replace.md
- wpf/Syntax-Editor/Basic-Editing/Selected-Text-Drag-and-Drop.md
Worked on site audit issues, merge these changes,
Regards,
Gowthaman
> SEO-2370_Site_Audit_Issues

- wpf/Multi-Column-DropDown/UIAutomation.md
- wpf/Syntax-Editor/Basic-Editing/Editing-Text-in-SyntaxEditor.md
- wpf/Syntax-Editor/Basic-Editing/Line-Numbers.md
- wpf/Syntax-Editor/Basic-Editing/Single-Line-Mode.md
Worked on site audit Missing h1 tags issues, merge these changes,
Regards,
Gowthaman
> SEO-2423_Site_Audit_Issues

- wpf/Classic/Chart/How-to/Export-SfChart-as-Image.md
- wpf/Diagram/Interaction/Deletion.md
- wpf/Diagram/Interaction/ZoomPan.md
Worked on site audit issues, merge these changes,
Regards,
Gowthaman
> SEO-2475_Site_Audit_Issues

- wpf/Diagram/Preview-Settings.md
Worked on site audit issues, merge these changes,
Regards,
Gowthaman
> SEO-2513_Site_Audit_Issues

- wpf/DataGrid/Column-Types.md
- wpf/DataGrid/FilterRow.md
- wpf/DataGrid/Localization.md
Resolved the improper link in WPF-Datagrid UG.
> WPF-60295 Resolved the improper link in Datagrid- UG

- wpf/Pdf-Viewer/Form-Filling-in-PDF.md
UG documentation for the tab index order support in PdfViewer.
[https://www.syncfusion.com/feedback/29074/tab-index-order-support-for-form-fields](https://www.syncfusion.com/feedback/29074/tab-index-order-support-for-form-fields)
This helps to move forward and backward through form fields.
[https://github.com/essential-studio/pdfviewer/pull/194](https://github.com/essential-studio/pdfviewer/pull/194)
> WPF-61797 UG for the Tab index order support

- wpf/Card-View/Localization.md
- wpf/Docking/Pattern-and-Practices.md
Removing the improper redirecting links.
> IN-18493-External-Redirect-Issue-hotfix

- wpf/OLAP-Common/Online-Analytical-Processing-OLAP.md
WPF-61143 - Broken URI's are updated
> WPF-61143 - Broken URI's updated

- wpf/Accordion/Getting-Started.md
- wpf/Accordion/Overview.md
- wpf/Accordion/Populating-Items.md
-Corrected the indent issues for WPF Ug documentation
-Added the capture tags in the code snippet block
> TEST-34404-Corrected the indent issues for WPF Ug documentation

- wpf/OLAP-Common/Online-Analytical-Processing-OLAP.md
> WPF-61143 -  Need to update the broken links in the mentioned page

- wpf/Diagram/Node.md
- wpf/Diagram/Snapping/CustomSnapping.md
Hi @ChristoIssac,
|Task Category| Pages With Redirect - Search console|
|:--|:--|
|Issue count| Help site links - 1000 |
|Fixed Count| Help site links - 2 |
|Analysis| Inspecting the links and found referring pages |
|Solution| replaced the exact URL instead of old URL |
|Hotfix PR| https://github.com/syncfusion-content/wpf-docs/pull/407 | 
|Task link|https://syncfusion.atlassian.net/browse/SEO-2684|
|Excel| N/A |
Regards,
Gowthaman
> SEO-2684-Coverage-Page-With-Redirect-UG

- wpf/Split-Button/Getting-Started.md
--Resolved the UG failures in WPF UG Documentation
> TEST-34404-Resolved the UG Failures For WPF documentation

- wpf/DataGrid/Export-To-Excel.md
- wpf/DataGrid/Grouping.md
- wpf/DataGrid/Master-Details-View.md
- wpf/DatePicker/Formatting.md
Hi @ChristoIssac,
|Task Category| Pages With Redirect - Search console|
|:--|:--|
|Issue count| Help site links - 1000 |
|Fixed Count| Help site links - 20 |
|Analysis| Inspecting the links and found referring pages |
|Solution| replaced the exact URL instead of old URL |
|Hotfix PR| https://github.com/syncfusion-content/wpf-docs/pull/418 | 
|Task link|https://syncfusion.atlassian.net/browse/SEO-2684|
|Excel| N/A |
Regards,
Gowthaman
> SEO-2684-Coverage-report-pages-with-redirect

- wpf/Breadcrumb/Getting-Started.md
- wpf/Classic/Diagram/Getting-Started.md
- wpf/DataGrid/Paging.md
- wpf/DataGrid/Row-Height-Customization.md
- wpf/Diagram/Diagram-Ribbon.md
- wpf/Diagram/Getting-Started.md
- wpf/Diagram/Overview-Control.md
- wpf/Diagram/Printing.md
- wpf/Docking/Dealing-with-Windows.md
- wpf/Docking/Getting-Started.md
- wpf/Docking/Tabbed-Window.md
- wpf/Gantt/Custom-Node-Style.md
- wpf/Gantt/Highlighting-Tasks.md
- wpf/Gantt/Zooming.md
- wpf/HeatMap/Getting-Started.md
- wpf/Maps/UserInteraction.md
- wpf/OLAP-Common/How-To/Connect-WCF-Service-by-an-additional-Binding-Type-in-silverlight-application.md
- wpf/Ribbon/GettingStarted.md
- wpf/Scheduler/Calendar-Types.md
- wpf/Tab-Navigation/Animation.md
- wpf/Tab-Navigation/Data-binding.md
- wpf/Tile-Control/Hub-Tile-Control.md
- wpf/ToolBar/Getting-Started.md
-Resolved the UG publishing failures
-Modified the indent issues in the ug documentation
> TEST-34403- Resolved the publishing failures in WPF UG documentation 

- wpf/Diagram/Interaction/Keyboard.md
Added missed short cut key commands for SfDiagram control.
> WPF-61988 Some short cut key commands are missing in UG

- wpf/Diagram/Stencil/Stencil.md
* Removed unwanted code snippets.
* Added updated code snippets
* Updated the sample and its code to latest code snippets and versions.
> WPF-62008  Correct inaccurate or outdated code samples and Code snippets in Stencil UG

- wpf/Breadcrumb/Getting-Started.md
- wpf/Chromeless-Window/TitleBarCustomization.md
- wpf/Grouping/Getting-Started.md
- wpf/Kanban-Board/Overview.md
- wpf/PropertyGrid/CategoryEditor-support.md
- wpf/Ribbon/RibbonMerge.md
-Corrected the indent changes in WPF ug
> TEST-34403-Corrected the indent changes in WPF ug

- wpf/Diagram/Stencil/Stencil.md
* Removed unwanted code snippets.
* Added updated code snippets
* Updated the sample and its code to latest code snippets and versions.
> WPF-62008 Correct inaccurate or outdated code samples and Code snippet

- wpf/Pdf-Viewer/pdf-rendering-engines.md
Content reviewed changes were added
> WPF-62236 Need to update arm pdfium details in UG documentation

- wpf/System-Requirements.md
- wpf/Themes/ScrollBar-Mode.md
- wpf/Themes/Skin-Manager.md
- wpf/Themes/Theme-Studio.md
- wpf/dotnet-core-compatibility.md
Updated the UG documents with Windows11 theme and .NET 6 contents and removed old contents.
> WPF-62372-Updated-UG-documents

- wpf/dotnet-core-compatibility.md
Added a opening row tag in a table in core compatibility document.
> WPF-62372-Modified UG documents

- wpf/Spreadsheet/Localization.md
I have removed the old resource file and added the Japanese resource file
> WF-62748 : Added the Proper Resource file for japanese

- wpf/Chromeless-Window/Customizing-Border-of-the-ChromelessWindow.md
- wpf/Chromeless-Window/TitleBarCustomization.md
Updated the UG document content for title bar customization page in WPF ChromelessWindow.
> WPF-62538 : Update the UG document content of title bar customization page in WPF ChromelessWindow (hotfix)

- wpf/Chromeless-Window/Customizing-Border-of-the-ChromelessWindow.md
- wpf/Chromeless-Window/TitleBarCustomization.md
Updated the UG document content for title bar customization page in WPF ChromelessWindow.
> WPF-62538 : Update the UG document content of title bar customization page in WPF ChromelessWindow

- wpf/Syntax-Editor/Language-Support/Supported-Languages.md
Updated the UG document content for Supported Language page in SyntaxEditor.
> WPF-62566 Add the link to DocumentLanguage

- wpf/Syntax-Editor/Language-Support/Supported-Languages.md
Updated the UG document content for Supported Language page in SyntaxEditor.
> WPF-62566 Add the link to DocumentLanguage 

- wpf/Themes/Skin-Manager.md
Removed alignment issues in Table while adding resource key list
> WPF-61684-Removed alignment issues in Table

- wpf/Percent-TextBox/Getting-Started.md
- wpf/Percent-TextBox/Range-Adorner.md
- wpf/PropertyGrid/Built-in-Editor-support.md
Hi Aishwarya,
Worked on page with redirect for help links, so merge these changes
Regards,
Gowthaman
> SEO-3146-coverage-page-with-redirect-help

- wpf/DataGrid/Data-Virtualization.md
Hi @susmitha-sundar ,
I have correct the broken links in DataVirtualization section in our DataGrid UG. Could you please review it and let me know if you have any concerns.
Ticket : https://support.syncfusion.com/agent/tickets/434071
Regards
Sathiyathanam
> WF-65153 - Need to correct the broken links in a DataVirtualization section in DataGrid UG

- wpf/Themes/Skin-Manager.md
Addressed all the allignment issues.
> WPF-62607-Resolved the alignment issues

- wpf/Syntax-Editor/Basic-Editing/Read-Only-Mode.md
Improve the codes in C# language for better understanding in the ReadOnlyMode file of edit control.
> WPF-62577 Improve illustration in edit control UG documentation

- wpf/ToolBar/Getting-Started.md
Please review the changes for WPF Page with redirect.
Regards,
Selline Rita.
> SEO-3161-WPF-Page-with-redirect

- wpf/DataGrid/Columns.md
- wpf/ReportViewer/TroubleShooting-Errors.md
Please review the changes for Page with redirect for WPF.
Regards,
Yvone.
> SEO-3239 WPF Page with redirect

- wpf/Pdf-Viewer/How-To/Disable-toolbar-items.md
- Updated the UG content for disable toolbar items
> WPF-62737 Updating the disable toolbar items page

- wpf/Syntax-Editor/Basic-Editing/Find-and-Replace.md
Added SubHeader to the FindandReplace window in EditControl.
> WPF-60497 : Adding SubHeader to the FindandReplace window in EditControl

- wpf/Tree-Navigator/Overview.md
Added more information and example on the WPF TreeNavigator overview page.
> WPF-61394 : Updated the overview page for TreeNavigator (hotfix)

- wpf/Gantt/How-To/Restrict-SelectionMode-as-Single.md
- wpf/Maps/How-To/transform-latitude-and-longitude-value-to-pixel-value-and-vice-versa.md
- wpf/Syntax-Editor/Language-Support/MarkupLanguageBase-Class.md
Worked on bing report issues, so merge these changes
Regards,
Gowthaman
> SEO-3261-bing-report-issues

- wpf/Charts/SeriesTypes/Spline.md
Added the additional explanation content for the Spline types.
> WPF-62704-Add Additional content for the Spline types.

- wpf/Upgrade/how-to-upgrade.md
Please review changes on WPF upgrade.
Regards,
Sharly A.
> SEO-3226 - WPF  changes

- wpf/Maps/Map-Providers.md
Worked on SEMrush issues, so merge these changes
Regards,
Gowthaman
> SEO-3356-semrush-report-issues

- wpf/ToolBar/Getting-Started.md
Added redirect link for windowsform links.
Regards,
Sharly A.
> SEO-3446 - WPF ToolBar permanent redirect

- wpf/DataGrid/Overview.md
- wpf/Linear-Gauge/Overview.md
- wpf/Radial-Gauge/Overview.md
Updated redirect links for Windows forms controls.
Regards,
Sharly A.
> SEO-3446 - WPF controls

- wpf-toc.html
- wpf/Pdf-Viewer/How-To/Change-the-new-toolbar-design-to-old-toolbar-design.md
Added the content review changes to the UG of changing the new toolbar design to old toolbar design
> DOC-5248 Review for the UG documentation for Changing new toolbar design to old toolbar design

- wpf/Pivot-Grid/PivotGrid-Getting-Started.md
- wpf/ToolBar/Getting-Started.md
- wpf/Welcome-to-Syncfusion-Essential-WPF.md
Added redirect link for wpf.
Regards,
Sharly A.
> SEO-3446-WPF

- wpf/Charts/Interactive-Features/Trackball.md
- wpf/DataGrid/Data-Virtualization.md
- wpf/DataGrid/Editing.md
- wpf/DataGrid/Export-To-Excel.md
- wpf/DataGrid/Export-To-PDF.md
- wpf/DataGrid/Filtering.md
- wpf/DataGrid/Paging.md
- wpf/DataGrid/Printing.md
- wpf/DataGrid/Row-Height-Customization.md
- wpf/DataGrid/Styles-and-Templates.md
Added redirect link for WPF Controls.
Regards,
Sharly A.
> SEO-3380 - WPF Control

- wpf/Charts/Interactive-Features/Trackball.md
- wpf/DataGrid/Data-Validation.md
- wpf/DataGrid/Data-Virtualization.md
- wpf/DataGrid/Styles-and-Templates.md
Changed http to https for UWP controls.
Regards,
Sharly A.
> SEO-3446 - WPF controls http to https

- wpf/DataGrid/Editing.md
- wpf/Tile-View/Working-with-TileView.md
Added redirect link for WPF.
Regards,
Sharly A.
> SEO-3446 - WPF redirect link

- wpf/System-Requirements.md
- wpf/arm-support.md
- wpf/dotnet-framework-compatibility.md
I have removed the  .Net 3.5 add .Net 7.0  support in WPF UG
> WF-65817 : Remove the .Net 2.0 and .Net 3.5 support and add the .Net70 support in Winforms and WPF UG

- wpf/Licensing/how-to-generate.md
Have changed redirect link in WPF, please check.
Regards,
Yvone.
> SEO-3297 WPF Redirect

- wpf/Pdf-Viewer/How-To/Change-the-new-toolbar-design-to-old-toolbar-design.md
- wpf/Pdf-Viewer/How-To/Disable-toolbar-items.md
Added the changes for the disable toolbar item contents based on new toolbar.
> WPF-62938 Documentation of old toolbar design from new toolbar design  in WPF PdfViewer

- wpf/Navigation-pane/Appearance.md
Added the end tab for the code snippet in Appearance.md file.
> WPF-61827 : Update the content for GroupBar control

- wpf/System-Requirements.md
- wpf/arm-support.md
- wpf/dotnet-framework-compatibility.md
Please find the development PR,
https://github.com/syncfusion-content/wpf-docs/pull/605/files
> WF-65817 : Remove the .Net 2.0 and .Net 3.5 support and add the .Net70 support in Winforms and WPF UG _Hotfix branch

- wpf/ComboBox/Blendability.md
- wpf/ComboBox/Watermark-Support.md
- wpf/Scheduler/Reminder.md
Worked on SEMrush report issues, so merge these changes
Regards,
Gowthaman
> SEO-3439-semrush-report-issues

- wpf-toc.html
Added the classic flag in notify icon.
> WPF-63006 : Add the classic flag in notify icon.

- wpf/DataGrid/Master-Details-View.md
Hi @gowthamanthavasiyappan,
Please find changes made.
Regards,
Scholar.
> SEO-3550 WPF changes

- wpf-toc.html
Hi Team,
Updated UG pages regarding the features included in Volume 1, 2023 release.
Feature 3: API to access the scrollbars of the SfRichTextBoxAdv control.
Regards,
> WPF-62905: UG documentation for the Volume 1 2023 features

- wpf/DataGrid/Editing.md
- wpf/DataGrid/Rows.md
Modify the code snippet and broken links
> 825811_Modify the broken link and code snippet

- wpf/TreeView/Data-Population.md
- wpf/TreeView/Getting-Started.md
WPF-63016 : Unwanted code snippets removed
> WPF-63016: Need to remove this code snippet "xmlns:syncfusion="http://schemas.syncfusion.com/wpf"“ from the unwanted places

- wpf/DataGrid/Performance.md
- wpf/TreeGrid/Columns.md
Have changed redirect links.
Regards,
Yvone.
> SEO-171350 WPF Redirect

- wpf/RichTextBox/Comment.md
Hi Team,
Updated WPF UG pages with the IsCommentPanelVisible API feature.
Regards,
> ES-825519-Update UG pages for IsCommentPanelVisible API feature.

- wpf/DataGrid/Master-Details-View.md
Have changed WPF redirect links, please review.
Regards,
Yvone.
> SEO-171762 WPF Redirect

- wpf/DataGrid/Data-Validation.md
- wpf/DataGrid/Getting-Started.md
- wpf/Pdf-Viewer/Getting-Started.md
- wpf/Percent-TextBox/Culture-and-Number-Formats.md
Please review the changes for WPF Page with redirect.
Regards,
Selline Rita.
> SEO-3560 - WPF Page With Redirect

- wpf/DataGrid/context-menu.md
- wpf/Diagram/DataSource.md
Hello, 
I have worked on the links with redirects.
Regards,
Beryl
> SEO-171719-Links-With-Redirects

- wpf/Split-Button/Multiline-Text-Support.md
- wpf/Syntax-Editor/Language-Support/LanguageBase-Members.md
Hi @gowthamanthavasiyappan ,
Have changed missing H1 in WPF.
Regards,
Yvone.
> SEO-172157WPF Missing H1

- wpf/DataGrid/Data-Binding.md
Description:
Task Details:
[UG documentation - 830095 - Modify the broken links in WPF-DataGrid User Guide Documentation](https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/830095)
Updated the below mentioned links:
> ES-830095-Modify the broken links in WPF-DataGrid User Guide Documentation

- wpf/Double-TextBox/Getting-Started.md
- wpf/PropertyGrid/Appearance.md
- wpf/ToolBar/Customization-of-ToolBarAdv.md
Hi @gowthamanthavasiyappan ,
Have worked on changing redirect links in WPF.
Regards,
Yvone.
> SEO-172160 WPF Redirect

- wpf/Pdf-Viewer/Working-with-Annotations/Squiggly-Annotation.md
Corrected the spell error for the squiggly documentation for the Pdfviewer
> Corrected Spell Error in squiggly documentation

- wpf/DataGrid/Column-Types.md
- wpf/DataGrid/FilterRow.md
- wpf/Spreadsheet/Formulas.md
ES-833697: I have added the ExcelLikeComputations property-related details in SfSpreadSheet UG documentation under the formulas section and modify the broken links in SfDataGrid
> ES-833697 Add the ExcelLikeComputations property related details

- wpf/Charts/Annotations.md
Have renamed image name alt, and changed folder name.
Regards,
Yvone.
> SEO-173296 WPF Chart Annontations

- wpf/Charts/Area.md
> SEO-173296 WPF Chart Area

- wpf/Charts/Getting-Started.md
> SEO-173296 WPF Chart Getting Started

- wpf/Charts/Header.md
Have renamed image folder, and changed image alt.
Regards,
Yvone.
> SEO-173296 WPF Chart Header

- wpf/Charts/Overview.md
> SEO-173296 WPF Chart Overview

- wpf/Charts/SeriesTypes/ColumnandBar.md
> SEO-173296 WPF Chart ColumnandBar

- wpf/Charts/Technical-Indicators.md
> SEO-173296 WPF Chart Technical Indicators

- wpf/Charts/Trendlines.md
> SEO-173296 WPF Chart Trendlines

- wpf/Charts/Legend.md
Have renamed image folder, and changed image alt.
Regards,
Yvone.
> SEO-173239 WPF Chart Legend

- wpf/Accordion/Getting-Started.md
- wpf/DataGrid/Clipboard-Operations.md
- wpf/DataGrid/Performance.md
Added redirect link.
Regards,
Sharly A.
> SEO-3557 - WPF Control

- wpf/Diagram/Themes.md
**Changes in the Existing Documentation:**
To change the end tag in the theme UG
> WPF-838075-To change the tag name in Theme UG

- wpf/Visual-Studio-Integration/Create-Project.md
Hello,
I have worked on the links with redirects.
Regards,
Beryl
> SEO-174295-Image-Alt-WPF

- wpf/Charts/Legend.md
- wpf/DataGrid/Data-Validation.md
- wpf/DataGrid/Data-Virtualization.md
- wpf/DataGrid/FilterRow.md
- wpf/DataGrid/Search.md
- wpf/DataGrid/Sorting.md
- wpf/TreeGrid/Export-To-Excel.md
Have worked on WPF Page with Redirect, please review.
Regards,
Yvone.
> SEO-174775 WPF Page with redirect

- wpf/Pdf-Viewer/Working-with-Annotations/Text-Annotation.md
Updating text annotation of PdfViewer
> Updating text annotation of PdfViewer

- wpf-toc.html
- wpf/RichTextBox/FAQ-Section/How-to-paste-WordDocument-from-DocIO-in-SfRichTextBoxAdv.md
Hi Team,
Added UG content for the PasteCommand with WordDocument from DocIO as parameter in SfRichTextBoxAdv
Regards,
> ES-838522-UG documentation for PasteCommand with WordDocument as Parameter

- wpf-toc.html
- wpf/RichTextBox/Spell-Check.md
Hi Team,
1. Added the sample link for the use of Customized dictionaries for spellcheck in SfRichTextBoxAdv control.
2.  Added the FAQ topic (How to identify whether the viewer is scrolled to the bottom of the SfRichTextBoxAdv)i n the toc file
Regards,
> ES-840281-UG documentation to add sample link for customized dictionaries for spell check

- wpf/DataGrid/Localization.md
- wpf/DataGrid/Master-Details-View.md
- wpf/DataGrid/Overview.md
- wpf/DataGrid/Styles-and-Templates.md
- wpf/DataGrid/Unbound-Column.md
- wpf/Diagram/Exporting.md
- wpf/PropertyGrid/Getting-Started.md
- wpf/PropertyGrid/Overview.md
Have changed Page with Redirect links.
Regards,
Yvone.
> SEO-174775 WPF Redirect  links

- wpf/Currency-TextBox/Getting-Started.md
- wpf/Currency-TextBox/Overview.md
- wpf/Diagram/Interaction/Dragging/Drag.md
- wpf/Double-TextBox/Getting-Started.md
- wpf/Gantt/Getting-Started.md
- wpf/GridControl/Printing.md
- wpf/Integer-TextBox/Overview.md
- wpf/Licensing/how-to-generate.md
- wpf/PropertyGrid/Appearance.md
- wpf/PropertyGrid/Getting-Started.md
Have worked on changing Page with Redirect links.
Regards,
Yvone.
> SEO-175190 WPF Page with Redirect

- wpf-toc.html
> 847601 - Add XlsIO in WPF UG - HF

- wpf/Pdf-Viewer/Organize-Pages.md
- wpf/Pdf-Viewer/Working-with-Annotations/Working-with-Annotations-Programmatically.md
UG content for Show annotations, Modified date and Clear all annotations.
> 2023-Vol3 UG content for Show annotations, Modified date and Clear all annotations.

- wpf/Visual-Studio-Integration/Add-Item.md
- wpf/Visual-Studio-Integration/Template-Studio.md
I have committed the WPF Template Studio UG content changes.
> EXT-175791

- wpf-toc.html
Add necessary information about Create a copy of the nodes and connectors using ctrl key
> WPF-846925-Add necessary information about Create a copy of the nodes and connectors using ctrl key

- wpf-toc.html
Hi all,
- With this PR, we have added DocIO & Presentation controls in WPF platform UG.
Regards,
Dharanitharan A
> ES-846833-Add DocIO & Presentation controls in WPF platform UG-hotfix

- wpf/Classic/Chart/How-to/Change-the-position-of-the-Chart-Legend.md
Hello,
I have worked on the missing H1.
Regards,
Beryl.
> SEO-174767-WPF-Missing-H1

- wpf-toc.html
Hi all,
- With this PR, we have modified the DocIO and Presentation page navigation link.
Regards,
Dharanitharan A
> ES-846833-Modified the DocIO and Presentation page navigation link

- wpf/Color-Picker/Overview.md
- wpf/DataGrid/Clipboard-Operations.md
- wpf/DataGrid/Data-Validation.md
- wpf/DataGrid/Export-To-PDF.md
- wpf/DropDown-Button/Data-Binding.md
- wpf/Radial-Gauge/Getting-Started.md
- wpf/Spreadsheet/Working-with-SfSpreadsheet.md
Have changed WPF Page with Redirect UG.
Regards,
Yvone.
> SEO-175659 WPF Page Redirect

- wpf/DataGrid/Merge-Cells.md
- wpf/Digital-Gauge/Getting-Started.md
- wpf/Spreadsheet/Cell-Customization.md
Have changed WPF Page with Redirect links.
Regards,
Yvone.
> SEO-175659 Page with Redirect WPF

- wpf-toc.html
Hi All,
Modify the TOC file for DocIo and Presentation Product.
Task Link: https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/851567
Regards
venkatesh
> ES-851567 Modify TOC File 

- wpf/Themes/ScrollBar-Mode.md
Modified the XAML code in the Theme md file.
> ES-836428 Changes the XAML code for current behavior.

- wpf/DataGrid/Filtering.md
- wpf/DataGrid/UI-Automation.md
- wpf/DataGrid/Unbound-Rows.md
- wpf/Diagram/Interaction/Selection.md
- wpf/Image-Editor/Save-Reset.md
- wpf/Installation/offline-installer/how-to-install.md
- wpf/Percent-TextBox/Getting-Started.md
- wpf/Radial-Gauge/Labels.md
- wpf/Tabbed-MDI-Form/Getting-Started.md
- wpf/Testing/coded-ui.md
Have changed page with redirect links.
Regards,
Yvone.
> SEO-176130 WPF Redirect

- wpf-toc.html
I have added XlsIO control UG redirect links.
> 854120 - XlsIOChanges - WPF

- wpf/Scheduler/Events.md
Hi @saiganesh-sakthivel ,
Added ViewChanged event UG documentation. Kindly review it and inform me if any changes required.
Regards,
Rishvanth C K
> 845598-Add ViewChanged event documentation in WPF Scheduler.

- wpf/Charts/Striplines.md
- wpf/Classic/RichTextBoxAdv/How-To/Bind-the-content-of-the-RichTextBoxAdv-By-Using-MVVM.md
- wpf/DataGrid/Filtering.md
- wpf/Diagram/Stencil/SymbolGroup.md
- wpf/Domain-UpDown/Getting-Started.md
- wpf/Introduction/Common-Supports.md
Please review the redirect link issue fixes.
Thanks.
Regards,
Edith.
> SEO-176496-WPF-UG-page-with-redirects-links

- wpf/DataGrid/Localization.md
- wpf/DataGrid/Styles-and-Templates.md
- wpf/Integer-TextBox/Appearance.md
- wpf/Pdf-Viewer/Localization.md
- wpf/TreeGrid/Data-Validation.md
Hello,
Worked on the links with redirects.
Regards,
Beryl.
> SEO-175653-WPF-Pages-With-Redirects

- wpf/ReportDesigner/data-extension.md
Hello,
I have worked on the missing H1
Regards,
Beryl.
> SEO-176113-WPF-Missing-H1

- wpf/Visual-Studio-Integration/Add-References.md
- wpf/Visual-Studio-Integration/Template-Studio.md
I have modified the UG content of WPF Template Studio
> EXT-1775 - I have modify the UG content

- wpf-toc.html
- wpf/RichTextBox/FAQ-Section/How-to-export-the-inserted-image-as-an-Embedded-image-in-HTML-in-SfRichTextBoxAdv.md
Hi Team,
Added UG content for the  ImageNodeVisited API in SfRichTextBoxAdv
Regards,
> ES-855567-UG documentation for  ImageNodeVisited API

- wpf/Charts/Annotations.md
- wpf/DataGrid/Grouping.md
- wpf/DataGrid/ToolTip.md
- wpf/GridControl/Testing.md
- wpf/Introduction/Common-Supports.md
- wpf/Multi-Column-DropDown/Selection.md
- wpf/Percent-TextBox/Overview.md
- wpf/TreeGrid/Data-Validation.md
- wpf/TreeView/load-on-demand.md
- wpf/Welcome-to-Syncfusion-Essential-WPF.md
Have made changes to the redirect links,
Please review.
Thanks.
Regards,
Edith.
> SEO-176838-WPF-page-with-redirect-links

- wpf/ComboBox/Getting-Started.md
- wpf/DataGrid/Grouping.md
- wpf/DataGrid/Paging.md
- wpf/DataGrid/Selection.md
- wpf/GridControl/Getting-Started.md
- wpf/Percent-TextBox/Changing-Percent-Value.md
- wpf/Spreadsheet/Find-and-Replace.md
- wpf/TabControl/Closable-tabs.md
- wpf/TreeGrid/Sorting.md
- wpf/TreeView/Getting-Started.md
Have made changes to the redirect links,
Please review.
Thanks.
Regards,
Edith.
> SEO-176838-WPF-page-with-redirects-links

- wpf/DataGrid/Filtering.md
- wpf/DataGrid/Getting-Started.md
- wpf/DataGrid/Rows.md
- wpf/TabControl/ContextMenu.md
Please review the changes in this PR.
Thanks.
Regards,
Edith.
> SEO-177303-WPF-redirect-links

- wpf/Pdf-Viewer/Form-Filling-in-PDF.md
Ug content for Syncing form fields
> Ug content for Syncing form fields

- wpf-toc.html
WPF-835373 UG Changes are added
> WPF-835373 UG Changes are added

- wpf/Ribbon/RibbonCustomization.md
Hi Team,
EndTab is not added, this cause failure and it has been fixed now.
> Failure cleared in Ribboncustomization UG

- wpf/Diagram/Commands/Flip.md
Resolved the conflicts in the WPF in hotfix to master.
> WPF-862159 Resolved conflicts in the Flip page

- wpf/Accordion/Appearence-and-Styling.md
I have updated the correct codesnippets in accordion expander style in WPF Accordion control.
> WPF-858817 : Updated the correct codesnippets for Accordion control

- wpf/Accordion/Populating-Items.md
Hello,
I have worked on links with redirects.
Regards,
Beryl.
> SEO-178943-Redirect-Links-WPF

- wpf/TreeGrid/Columns.md
Hello, 
I have worked on links with redirects.
Regards,
Beryl.
> SEO-178943-WPF-Redirect-Links

- wpf/Pdf-Viewer/Getting-Started.md
Please review the redirect link changes made
Thanks.
Regards,
Edith.
> SEO-178901-WPF-page-with-redirect

- wpf/Charts/Technical-Indicators.md
- wpf/Range-Slider/How-To.md
- wpf/Spreadsheet/Rows-and-Columns.md
- wpf/Themes/Skin-Manager.md
- wpf/Tile-View/Data-Binding-Support.md
Please review the redirect link changes made
Thanks.
Regards,
Edith.
> SEO-178901-wpf-ug-page-with-redirect-links

- wpf/Docking/Docking-Window.md
- wpf/DropDown-Button/Getting-Started.md
- wpf/Tile-View/Getting-Started.md
Hi @MallikaRK 
Kindly review my PR in page with redirect UG help under WPF.
Regards.
Dickson J
> SEO-174654-WPF-Fast-Controls-Help

- wpf/Currency-TextBox/Culture-and-Number-Formats.md
- wpf/Double-TextBox/Culture-and-Number-Formats.md
I have worked on redirection links, please review.
Regards,
Scholar.
> SEO-179238-Page-with-redirect

- wpf/Currency-TextBox/Culture-and-Number-Formats.md
- wpf/DataGrid/Export-To-PDF.md
Have worked on Page with Redirect links.
Regards,
Yvone.
> SEO-178115 WPF Redirect

- wpf/Syntax-Editor/Language-Support/ProceduralLanguageBase-Class.md
Hi @MallikaRK,
I have worked on missing H1, please review
> SEO-178959-Missing-H1

- wpf/Accordion/Getting-Started.md
Hi @MallikaRK,
please review the changes made.
Thanks.
Regards,
Edith.
> SEO-178901-WPF-ug-page-with-redirect-links(1)

- wpf/Smith-Chart/Getting-Started.md
Please review the changes made.
Regards,
Scholar.
> SEO-179238-Redirection-links

- wpf/Digital-Gauge/DatePicker/Formatting.md
Have changed Page with Redirect links.
Regards,
Yvone.
> SEO-179238 WPF Page with Redirect

- wpf/Spreadsheet/Interactive-Features.md
- wpf/Spreadsheet/Printing.md
- wpf/Spreadsheet/Ribbon-Customization.md
- wpf/Spreadsheet/Selection.md
I have made changes for http links as proposed.
Regards,
Jeffrey
> Changed HTTP links

- wpf/Diagram/Commands/Delete.md
- wpf/Diagram/Connector/AppearanceAndValidation.md
- wpf/Diagram/Serialization.md
To Update Samples location in WPF UG.
> WPF-870840-To ensure the Samples location in UG and KB

- wpf/Diagram/Commands/Command-Manager.md
- wpf/Diagram/Commands/Grouping.md
WPF-872904 Ungroup command UG updated
> WPF-872904 Ungroup command UG updated

- wpf/Pdf-Viewer/Getting-Started.md
871182  Apply themes support code snippet for PdfViewer Control
> 871182  Apply themes support code snippet for PdfViewer Control

- wpf/Charts/FastChart/Fast-Series.md
- wpf/PropertyGrid/Getting-Started.md
- wpf/TaskBar/Changing-the-flow-directions.md
- wpf/TreeGrid/Interactive-Features.md
Kindly review the changes.
Regards,
Edith.
> SEO-180844-wpf-issue-fix

- wpf/Pdf-Viewer/Bookmark-Navigation.md
- wpf/Pdf-Viewer/Form-Filling-in-PDF.md
> Updated the proper alignment

- wpf/Image-Editor/serialization.md
Added API links to the WPF image editor control
> 874842 - Added a API links to WPF image editor

- wpf/Pdf-Viewer/How-To/Disable-toolbar-items.md
876589 How disable open button item alone in FileToggleButton if WPF Pdf viewer
> 876589 How disable open button item alone in FileToggleButton if WPF Pdf viewer

- wpf/Diagram/Scroll-Settings/ScrollLimit.md
Worked on wpf diagram changes.
Regards,
Sharly A.
> SEO-180850-WPF-Diagram-Changes

- wpf/Accordion/Selecting-Items.md
- wpf/Breadcrumb/Populating-Data.md
Have worked on Page with Redirect, please check.
Regards,
Yvone.
> SEO-181417 WPF Redirect links

- wpf/Circular-ProgressBar/Appearance.md
Updating documentation for circular progress bar
> Updating documentation for circular progress bar

- wpf/ComboBox/MultiSelection-Support.md
- wpf/TabControl/Closable-tabs.md
- wpf/TreeMap/ColorMapping.md
Kindly review the changes.
Regards,
Edith.
> SEO-180844-wpf-page-with-redirect-UG

- wpf/Integer-TextBox/Getting-Started.md
Kindly review the changes.
Regards,
Edith.
> SEO-180844-wpf-page-with-redirect-issue-fixes

- wpf/Pdf-Viewer/Viewing-PDF-Files.md
HI All,
I completed my draft work for Load Multiple PDf files in WPF PDF Files.
Task Link :<a href="https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/881611">Need to Include UG for whether we need to unload externally, before loading new document in PdfViewer</a>
Regards
Venkatesh
> ES 881611 Avoid exception while loading PDF Document

- wpf/DataGrid/Serialization-and-Deserialization.md
- wpf/DataGrid/autosize-columns.md
- wpf/DataGrid/context-menu.md
Hi @MallikaRK,
Worked on WPF-Changes.
Regards,
Sharly A.
> SEO-181938-WPF-Changes

- wpf/TreeGrid/Selection.md
Hi @gowthamanthavasiyappan ,
Kindly review the referring links issue fixed.
Thanks.
Regards,
Edith.
> SEO-180844-WPF-refering-page

- wpf/Gantt/Strip-Lines.md
- wpf/TimePicker/Getting-Started.md
- wpf/TreeGrid/Data-Binding.md
Hi @gowthamanthavasiyappan,
Kindly review the referring links issue fixes changes.
Thanks.
Regards,
Edith.
> SEO-180844-wpf-refering-page-issues

- wpf/Pdf-Viewer/How-To/Disable-toolbar-items.md
HI All,
I complete my drafting work of Include notes to instruction where to disable the toolbar items .
Task Link: <a href="https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/883309">Include notes to instruction where to disable the toolbar items </a>
Regards,
Venkatesh
> ES-883309 Disable Tool bar items

- wpf/DataGrid/Unbound-Column.md
Have worked on Page with Redirect links.
Regards,
Yvone.
> SEO-183465 WPF Page with Redirect

- wpf/Themes/Skin-Manager.md
- wpf/Themes/Theme-Studio.md
Hi @SubashiniMahendran,
I have prepared a UG document in WPF for the Vol 2 2024 release. Kindly review and merge the changes.
Regards,
Yuvaraj M
> 889792- Prepared a UG document for vol 2 2024 release.

- wpf/Gantt/drag-drop.md
- wpf/Gantt/filtering-sorting.md
- wpf/Gantt/getting-started.md
- wpf/Gantt/migrate-from-sftreegrid.md
Addressed GanttControl review correction changes
> 890013 - WPF GanttControl review correction changes

- wpf/Carousel/How-To/Change-SelectedItem-Position.md
Have worked on missing H1, please review.
Regards,
Yvone.
> SEO-183463 WPF Missing H1

- wpf/Scheduler/Appointments.md
- wpf/Scheduler/DaysView.md
- wpf/Scheduler/Month-View.md
- wpf/Scheduler/TimelineView.md
I have updated the API link for the tooltip and changed the code headings.
> WPF 890011 - Updated API links for Scheduler tooltip content

- wpf/Diagram/Rulers.md
- wpf/Diagram/Stencil/Commands.md
- wpf/Diagram/Stencil/Interactions.md
UG conflicts in the Diagram are fixed
> WPF-890318 UG conflicts in Diagram is fixed

- wpf/Diagram/Stencil/SymbolGroup/SymbolGroup.md
WPF-890318 UG Diagram tag issue is fixed
> WPF-890318 UG Diagram tag issue is fixed

- wpf/Diagram/Rulers.md
- wpf/Diagram/Stencil/Commands.md
- Added the SubHeading in Ruler's Page
- Formatted the C# code in Commands Page
> WPF-888738-Corrected the Issues

- wpf/Diagram/Node.md
> WPF-889895-Node issues fixed

- wpf/Diagram/BPMN-Shapes/BPMN-Connectors.md
- Corrected the Connector casting
> WPF-889895-BPMNShapes Connector Casting Issue

- wpf/Diagram/BPMN-Shapes/BPMN-Expanded-Sub-Process.md
- wpf/Diagram/BPMN-Shapes/BPMN-Group.md
Modified the paths for the Stencil and BPMN Shapes Palette to absolute URLs from their previous relative paths.
> WPF-889895-Updated the links to Stencil and BPMN Shapes Palette from relative path to URL

- wpf/Diagram/Port/Port.md
- wpf/Diagram/Port/PortHoverEffect.md
Corrected the issue of "note" section not displaying correctly and also corrected the Grammar mistakes
> WPF-889895-Corrected the Issues

- wpf/CheckedListBox/Check-items.md
- wpf/CheckedListBox/Data-Binding.md
- wpf/CheckedListBox/Layout-Related-Features.md
- wpf/CheckedListBox/Overview.md
- wpf/CheckedListBox/Sorting.md
Hi @gowthamanthavasiyappan,
I have fixed the redirection links, please review.
Regards,
Scholar.
> SEO-182428-page-with-redirect

- wpf/HeatMap/Overview.md
Have modified title, H1 and description, please review.
Regards,
Yvone.
> SEO-184192 WPF Heatmap Page with Redirect

- wpf/Gantt/baseline-support.md
- wpf/Gantt/import-and-export-support.md
- wpf/Gantt/zooming.md
I have updated the Gantt UG review corrections.
> WPF 886828 - Updated Gantt UG review corrections

- wpf/Gantt/auto-update-hierarchy.md
- wpf/Gantt/baseline-support.md
- wpf/Gantt/calendar-customization.md
- wpf/Gantt/custom-schedule.md
- wpf/Gantt/custom-tooltip.md
- wpf/Gantt/datetime-indicator-customization.md
- wpf/Gantt/dependency-relationship.md
- wpf/Gantt/getting-started.md
- wpf/Gantt/highlighting-tasks.md
- wpf/Gantt/import-and-export-support.md
- wpf/Gantt/migration-to-26v-or-higher.md
- wpf/Gantt/strip-lines.md
- wpf/Gantt/zooming.md
I have resolved API link issues in Gantt UG.
> WPF 886828 - Resolved Gantt UG API link issue

- wpf/Diagram/Commands/Command-Manager.md
- Formatted the C# code
- Corrected the sentence alignment
- Removed unwanted highlight
> WPF-889895- Corrected the Issues

- wpf/Pdf-Viewer/Printing-PDF-Files.md
Include Silent printing with printer name
> 883480 Include Silent printing with printer name

- wpf/Breadcrumb/How-To/Using-the-Refresh-button.md
Hi @Girija-Rajendran,
Have worked on Multiple H1, please review.
Regards,
Yvone.
> SEO-185532 WPF Multiple H1

- wpf/Bullet-Graph/Getting-Started.md
- wpf/Charts/CodedUI.md
- wpf/DataGrid/Styles-and-Templates.md
- wpf/DataGrid/UI-Automation.md
- wpf/Grouping/Overview.md
- wpf/Introduction/System-Requirement.md
- wpf/Range-Selector/Getting-Started.md
- wpf/Sparkline/Getting-started.md
- wpf/System-Requirements.md
- wpf/Testing/coded-ui.md
- wpf/TreeGrid/UI-Automation.md
- wpf/Visual-Studio-Integration/Add-References.md
- wpf/Visual-Studio-Integration/Overview.md
Hi @SubashiniMahendran 
I have removed the VS 2008,2010,2012, and 2013 for the WPF platform. Please review and merge the changes.
Regards 
Yuvaraj M
> 897889- Removed the VS 2008,2010,2012, and 2013 for the WPF platform.

- wpf/Visual-Studio-Integration/Template-Studio.md
1. The WPF UG has been comprehensively updated to include sections on NuGet Entry, Dependency Injection (DI) Setup, PageServices integration, and details on managing Resource files. Additionally, existing content has been reviewed and refined to correct inaccuracies and eliminate duplicate information.
> WPF Template Studio UG Improvements

- wpf/Visual-Studio-Integration/Template-Studio.md
1. The WinForms and WPF UG has been comprehensively updated to include sections on NuGet Entry, Dependency Injection (DI) Setup, PageServices integration, and details on managing Resource files. Additionally, existing content has been reviewed and refined to correct inaccuracies and eliminate duplicate information.
> WinForms and WPF Template Studio UG Improvements

- wpf/Tile-View/Data-Binding-Support.md
Hi Team,
We have documented the limitation of RowHeight and ColumnWidth properties.
> WPF-900690 TileView Virtualization content updated

- wpf/Control-Dependencies.md
- wpf/Gantt/migration-to-26v-or-higher.md
- wpf/Surface-Chart/Getting-Started.md
- Update the UG for surface chart new theme support.
- Removed dependent assemblies from control dependencies for scheduler (Themes MaterialLight) and Gantt (Themes MaterialLight & SfSkinManager).
> 892307-Update theme support in surface chart documents.

- wpf-toc.html
- wpf/Pdf-Viewer/Changing-the-Current-User.md
- wpf/Pdf-Viewer/How-To/Changing-the-Current-User.md
Description :
Add the UG documentation for CurrentUser API
> CurrentUser API UG documentation

- wpf-toc.html
Task - https://dev.azure.com/Syncfusion-Infrastructure/Install/_workitems/edit/187726/
> 187726 - Syncfusion License Validation Page Location Updated - Live

- wpf/Scheduler/Month-View.md
I have updated the Default value for the Month view setting's Date Format in WPF scheduler UG documentation.
> 906867- Update the default value for Date Format  in WPF Scheduler.

- wpf/Visual-Studio-Integration/Template-Studio.md
Need to resolve WPF Conflict issues, due to space differs conflict occurred, I resolved by copy files from Development to Master branch.
> WPF Conflict Resolved

- wpf/ToolBar/ToolBarAdv-state.md
Update the ToolBarStateChangedEvent description in ToolBarAdv's UG documentation in WPF.
> WPF-910709 : Update the ToolBarStateChangedEvent description in ToolBarAdv's  UG documentation in WPF.

- wpf/ToolBar/ToolBarAdv-state.md
Update the ToolBarStateChangedEvent description in ToolBarAdv's UG documentation in WPF.
> WPF-910709 : Update the ToolBarStateChangedEvent description in ToolBarAdv's UG documentation in WPF.

- wpf/Pdf-Viewer/Saving-the-PDF-document.md
Description :
Add the UG documentation for canceling save in save events
> UG about canceling save in save events

- wpf/Pdf-Viewer/Working-with-Annotations/Text-Annotation.md
Description : 
Add UG documentation for changing the Font Family of Free text annotation
> UG documentation about changing the Font Family of Free text annotation

- wpf/System-Requirements.md
- wpf/dotnet-core-compatibility.md
Hi @SubashiniMahendran
I have updated .Net 9.0 in WPF System Requirements. Please review and merge the changes
Regards
Yuvaraj M
> Update Net 90 changes

- wpf/System-Requirements.md
Hi @SubashiniMahendran,
I have removed the preview vs system requirements for WPF Platform. Kindly review and merge the changes.
Regards
Yuvaraj M
> Net90 changes

- wpf/DataGrid/Serialization-and-Deserialization.md
Hi @Yvone-Atieno  
|Title|Description|
|--|--|
|Task Category| Site Audit
|Content Task Link/Mail Screenshot| NA|
|UX task| NA|
|Hotfix PR||
|Ticket/Task link|https://github.com/syncfusion-content/wpf-docs/pull/1551|
|Excel/SharePoint link| NA|
|Changes made|Reason for changes|
|--|--|
|Updated valid links| To resolve redirection links|
Regards,
Lydia A.
> SEO-192030 WPF DataGrid http to https

- wpf/Chromeless-Window/Styling-the-ChromelessWindow.md
- wpf/Integer-TextBox/Culture-and-Number-Formats.md
- wpf/TreeGrid/Export-To-Excel.md
Hi @Yvone-Atieno 
|Title|Description|
|--|--|
|Task Category|Site Audit - Page with redirect|
|Content Task Link/Mail Screenshot| NA|
|UX task| NA|
|Hotfix PR|https://github.com/syncfusion-content/wpf-docs/pull/1555|
|Ticket/Task link| https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/191923|
|Excel/SharePoint link| NA|
|Changes made|Reason for changes|
|--|--|
|Changed redirect link  |  To avoid redirection 301 or 302,providing direct link    |     
Regards,
Hillary
> SEO-191923--wpf-page-with-redirect

- wpf/Pdf-Viewer/Working-with-command-binding/Binding-commands-to-a-button.md
**Description:**
Created UG for the working with commands section by adding UG content for the missing commands
*  This code change is for the working with commands section in WPF- PdfViewer.
*  Added detailed descriptions, examples, and guidelines for the missing commands with code examples.
*  Improved clarity and structure of the UG for ease of understanding of the UG.
> 559101 - Update the "Working with commands" UG contents

- wpf/RichTextBox/Localization.md
Hi Team,
The resource files mentioned in the Localization section of SfRichTextBoxAdv have been updated, and samples have been added for them.
UG Location: https://help.syncfusion.com/wpf/richtextbox/localization 
Regards,
> ES-917773: Updated resource file and added sample for Localization

- wpf/Syntax-Editor/RoutedUICommands.md
Modified and added contents for the Commands and their Default Shortcut keys in WPF EditControl UG documentation
> WPF-921021_Prepared UG documentation for Commands and their Default Shortcut keys in WPF EditControl

- wpf/Diagram/Stencil/ContextMenu.md
- Updated stencil's context menu content
> WPF-925464-Stencil_ContextMenu_Revamp

- wpf/Diagram/Interaction/Keyboard.md
- wpf/Diagram/Scroll-Settings/ScrollLimit.md
Updated UG Documentation for the Feature of Scrolling support to the Diagram Page using Arrow Keys.
For more details refer to the PR Link: (https://github.com/essential-studio/sfdiagram-xaml/pull/756)
> WPF-925467-UG for Scrolling support to Diagram Using Arrow Keys.

- wpf/Diagram/Serialization.md
Added Content for Mermaid Text to Diagram Support
> WPF-925461-Mermaid_Support_UG_Content

- wpf-toc.html
- wpf/Diagram/Stencil/Appearance.md
- wpf/Diagram/Stencil/Serialization.md
- Added content for stencil save and load 
- Also added content for stencil symbol group import and export
- **Corrected stencil display mode images**
> WPF-925462-Stencil_And_SymbolGroup_Save_Load_Content

- wpf/dotnet-framework-compatibility.md
Hi @SubashiniMahendran ,
I have modified dotnet-framework-compatibility content. Kindly review and merge the changes.
Regards,
Yuvaraj M
> Modified dotnet-framework-compatibility content

- wpf-toc.html
- wpf/AI-AssistView/Getting-started.md
- wpf/AI-AssistView/Overview.md
- wpf/AI-AssistView/Suggestions.md
- wpf/AI-AssistView/Typing-indicator.md
- wpf/AI-AssistView/open-ai.md
UG documentation for AIAssistView in WPF control.
> Ug documentation for AIAssistView in WPF Control.

- wpf-toc.html
- wpf/AI-AssistView/Getting-Started.md
- wpf/AI-AssistView/Open-AI.md
- wpf/AI-AssistView/Overview.md
- wpf/AI-AssistView/Suggestions.md
- wpf/AI-AssistView/Typing-Indicator.md
UG documentation for AIAssistView control.
> UG documentation for AIAssistView control.[master]

- wpf-toc.html
- wpf/Diagram/Stencil/Appearance.md
- wpf/Diagram/Stencil/Serialization.md
- Added content for stencil save and load 
- Also added content for stencil symbol group import and export
- **Corrected stencil display mode images**
> WPF-925462-Stencil And SymbolGroup Save Load Content HotFix

- wpf/Diagram/Stencil/Serialization.md
- wpf/Diagram/Stencil/SymbolGroup/SymbolGroup.md
- wpf/Diagram/Themes.md
- Added Note In Themes
- Fixed the issue of image not visible, in SymbolGroup content
> WPF-925465-Added Note In Themes

- wpf-toc.html
- wpf/TreeMap/Accessibility.md
I have updated the UG documentation to include accessibility support for the WPF TreeMap.
> 925962 - [hotfix] Update the Accessibility support  for WPF TreeMap UG documentation.

- wpf/Gantt/data-binding.md
- wpf/Image-Editor/Text.md
Update the Image Editor Text Settings content.
> 925962- Update the Image Editor Text Settings content.

- wpf/Pdf-Viewer/Bookmark-Navigation.md
Update the code sample in "Programmatically navigate to a bookmark destination"
> 559099-Update the code sample in "Programmatically navigate to a bookmark destination" and publish a sample

- wpf/Add-Syncfusion-Controls.md
- wpf/Blend-Support.md
- wpf/Control-Dependencies.md
- wpf/Installation/install-nuget-packages.md
- wpf/Localization.md
- wpf/Pattern-and-Practices.md
- wpf/System-Requirements.md
- wpf/Themes/Fluent-Theme.md
- wpf/Themes/Keyboard-Focus-Visual.md
- wpf/Themes/ScrollBar-Mode.md
- wpf/Themes/Skin-Manager.md
- wpf/Themes/Theme-Studio.md
- wpf/Themes/Touch-Support.md
- wpf/Welcome-to-Syncfusion-Essential-WPF.md
- wpf/arm-support.md
- wpf/dotnet-core-compatibility.md
- wpf/dotnet-framework-compatibility.md
- wpf/right-to-left.md
- wpf/samples.md
Hi @SubashiniMahendran
I have included the TradeMark symbol in the hotfix WPF UG Document. Kindly review and merge the changes.
Regards,
Yuvaraj M
> Include trademark symbol in WPF UG document

- wpf/Add-Syncfusion-Controls.md
- wpf/Blend-Support.md
- wpf/Control-Dependencies.md
- wpf/Installation/install-nuget-packages.md
- wpf/Localization.md
- wpf/Pattern-and-Practices.md
- wpf/System-Requirements.md
- wpf/Themes/Fluent-Theme.md
- wpf/Themes/Keyboard-Focus-Visual.md
- wpf/Themes/ScrollBar-Mode.md
- wpf/Themes/Skin-Manager.md
- wpf/Themes/Theme-Studio.md
- wpf/Themes/Touch-Support.md
- wpf/Welcome-to-Syncfusion-Essential-WPF.md
- wpf/arm-support.md
- wpf/dotnet-core-compatibility.md
- wpf/dotnet-framework-compatibility.md
- wpf/right-to-left.md
- wpf/samples.md
Hi @SubashiniMahendran
I have included the Trademark symbol in the WPF UG Document. Kindly review and merge the changes.
Regards,
Yuvaraj M
> Modified Trademark symbol from unicode to superscript registered trademark symbol

- wpf/Diagram/Connector/DefineConnector.md
- wpf/Diagram/Interaction/Selection.md
- wpf/Diagram/Node.md
- wpf/Diagram/Tools.md
The KB articles mentioned below are linked in the WPF UG.
- https://support.syncfusion.com/kb/article/18899/how-to-obtain-the-completed-status-of-a-polyline-connector-in-the-wpf-diagram-sfdiagram
- https://support.syncfusion.com/kb/article/18896/how-to-select-the-node-that-is-outside-of-the-selection-region-in-the-wpf-diagram-sfdiagram
> WPF-934487-Need to link the KBs in UG

- wpf/Add-Syncfusion-Controls.md
- wpf/Pattern-and-Practices.md
- wpf/Themes/Skin-Manager.md
- wpf/Themes/Theme-Studio.md
- wpf/VPAT.md
- wpf/Welcome-to-Syncfusion-Essential-WPF.md
- wpf/dotnet-core-compatibility.md
Hi @SubashiniMahendran
I added missed trademark symbol in WPF UG common files. Kindly merge the changes.
Regards,
Yuvaraj M
> Added missed trademark symbol in WPF UG common files.

- wpf/Diagram/Connector/DefineConnector.md
- wpf/Diagram/Node.md
WPF-925458 Diagram conflict issues are fixed
> WPF-925458 Diagram conflict issues are fixed

- wpf/Diagram/Connector/DefineConnector.md
- wpf/Diagram/Node.md
WPF-925458 Diagram conflicts are fixed
> WPF-925458 Diagram conflicts are fixed

- wpf/Welcome-to-Syncfusion-Essential-WPF.md
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>
<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>
<div style='direction:ltr;border-width:100%'>
<div style='direction:ltr;margin-top:0in;margin-left:0in;width:7.7416in'>
<div style='direction:ltr;margin-top:0in;margin-left:0in;width:7.7416in'>
<div style='direction:ltr'>
-- | --
Task Link | IN -   198113 Updating Banner Content in Documentation
Feature description | To   update the content in the overview pages
Analysis and design | N/A
Output screenshots | N/A
Areas affected and ensured | Changes …
> Update Banner Dev

- wpf/Welcome-to-Syncfusion-Essential-WPF.md
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>
<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>
<div style='direction:ltr;border-width:100%'>
<div style='direction:ltr;margin-top:0in;margin-left:0in;width:7.7416in'>
<div style='direction:ltr;margin-top:0in;margin-left:0in;width:7.7416in'>
<div style='direction:ltr'>
-- | --
Task Link | IN -   198113 Updating Banner Content in Documentation
Feature description | To   update the content in the overview pages
Analysis and design | N/A
Output screenshots | N/A
Areas affected and ensured | Changes …
> Update Banner Content Hotfix

- wpf/Pdf-Viewer/pdf-rendering-engines.md
**Description :** 
- Updated the UG documentation of the WPF PdfViewer for the newly generated Pdfium version
> 944821 - UG documentation for the Pdfium version in PdfToImageConverter

- wpf/Visual-Studio-Integration/Template-Studio.md
Update WPF extension UG to Reflect Removal of .NET 6.0 and .NET 7.0 Support.
> Update extension UG to Reflect Removal of .NET 6.0 and .NET 7.0 Support

- wpf/Diagram/Stencil/Serialization.md
Updated UG Documentation for the Feature of Save and Load support to the Stencil Serialization in WPF Diagram.
For more details refer to the PR Link: https://github.com/essential-studio/sfdiagram-xaml/pull/786
> WPF-946343-Need to prepare a UG for explaining the Stencil Save and Load methods.

- wpf-toc.html
Marked the NotifyIcon control as Classic control.
> WPF- 931860 : Marked the NotifyIcon as Classic control 

- wpf/Docking/Dealing-with-Windows.md
Added CloseMode for the child item in DockingManager.
> 945899 - Updated the Closemode for the child item in DockingManager

- wpf/Diagram/Serialization.md
- wpf/Diagram/UML_Sequence_Diagram/Sequence-Diagram.md
- Corrected the mistakes in UG
- Also updated the API links
> WPF-946687-Corrected the mistakes in UG

- wpf/Pdf-Viewer/Working-with-Annotations/Stamp-Annotation.md
**Description:**
- Updated the UG for the GitHub sample on adding standard stamps to the toolbar.
> 558682 - Include the sample for the documentation “Adding your standard stamps in the toolbar”.

- wpf/Pdf-Viewer/Overview.md
Description :
Add the UG documentation for RTL
> 260501 : Add UG documentation for RTL in WPF

- wpf/Pdf-Viewer/Working-with-Annotations/Highlight-Annotation.md
- wpf/Pdf-Viewer/Working-with-Annotations/Squiggly-Annotation.md
- wpf/Pdf-Viewer/Working-with-Annotations/Strikethrough-Annotation.md
- wpf/Pdf-Viewer/Working-with-Annotations/Underline-Annotation.md
Description :
Add UG documentation for set color for a particular annotation in textmarkup annotation
> 558688 : Add UG documentation for set color for a particular annotation in textmarkup annotation in WPF 

- wpf-toc.html
The toc file updated for the UML Sequence Diagram.
> WPF-956314 - Need to update the toc file for the UML Sequence Diagram 

- wpf-toc.html
- wpf/Pdf-Viewer/How-To/Determine-the-current-point-in-a-Page.md
**Description:**
- Added UG for getting the current point in the PDFViewer
- Added a separate file in the How to Section
> 939407 - Documentation about getting the current point in the WPF PdfViewer

- wpf/dotnet-core-compatibility.md
- wpf/dotnet-framework-compatibility.md
Updated the dotnet-framework and core-compatibility support details in the WPF-docs
Link: https://help.syncfusion.com/wpf/dotnet-framework-compatibility#version-compatibility 
https://help.syncfusion.com/wpf/dotnet-core-compatibility#version-compatibility
> UG957457 - Updated the dotnet-core-compatibility support details

- wpf/PropertyGrid/Built-in-Editor-support.md
Updated documentation for the PropertyGrid control Built-in-Editor
Before Content Update
After Content Update
> WPF-959319_Updated documentation for the PropertyGrid control Built-in-Editor

- wpf/Chromeless-Window/Getting-Started.md
Corrected code snippet content for the Getting Started of ChromelessWindow control.
> WPF-957611_Corrected code snippet content for the Getting Started of ChromelessWindow control

- wpf/Menu/Animation-Support.md
- wpf/Menu/Binding-and-DataTemplate-Support.md
- wpf/Menu/Check-Box-and-Radio-Button-Support.md
- wpf/Menu/Command-Binding-and-Command-Target-Support.md
- wpf/Menu/Customizing-Data-Templates.md
- wpf/Menu/Data-Binding.md
- wpf/Menu/Icon-Support.md
- wpf/Menu/InputGestureText-Support.md
- wpf/Menu/Orientation-Support.md
- wpf/Menu/Scroll-Support.md
Check and change the code snippet misalignment, mistakes and errors in WPF MenuAdv controls UG.
**Menu:**
- Animation-Support
- Binding and DataTemplate support
- Check Box and Radio Button support
- Command Binding and Command Target Support
- Customizing Data Templates
- Data Binding
- Icon Support
- Input Gesture Text Support
- Orientation support
- Scroll Support.
> 964819-Check and change the code snippet misalignment, mistakes and errors in WPF MenuAdv controls UG

- wpf-toc.html
- wpf/Themes/Skin-Manager.md
Updated the SfSkinManager UG Changes
> Updated the SfSkinManager UG Changes

- wpf/Themes/Theme-Studio.md
Added the note content for theme export projects issue in NET 8.0/NET 9.0 projects.
> Updated the documentation for theme export projects issue

- wpf/Themes/Theme-Studio.md
Added the note content for theme export projects issue in NET 8.0/NET 9.0 projects.
> Updated the note content for skinmanager changes

- wpf/Pdf-Viewer/extract-text-from-PDF.md
Hi @MallikaRK 
-- | --
|Task Category |The title tag contains additional tags.|
|Ticket/Task link| https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/204819|
|Share point|[ Share point](https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B46FA712A-ABF2-4191-AC82-ADA0730216FB%7D&file=Syncfusion%20domain.xlsx&action=default&mobileredirect=true)|
Changes Made | Reason for change |
|-- | -- |
|Change the title tag contains additional tags. | delete the <sup>&reg;</sup> | 
Regards, 
Asha
> SEO-204819-Title-tag-Wpf-Hotfix

- wpf/TreeGrid/Clipboard-Operations.md
- wpf/TreeGrid/Column-Sizing.md
- wpf/TreeGrid/Columns.md
- wpf/TreeGrid/Data-Binding.md
- wpf/TreeGrid/Editing.md
- wpf/TreeGrid/Filtering.md
- wpf/TreeGrid/Getting-Started.md
- wpf/TreeGrid/Selection.md
- wpf/TreeGrid/Sorting.md
**Description:**
Resolving the formatting issues, link issues for the WPF DataGrid controls [User Guide documentation. ](https://help.syncfusion.com/wpf/welcome-to-syncfusion-essential-wpf)
> ES-974685 - Review the User Guide documentation and fix formatting issues, ensuring link accuracy

- wpf-toc.html
**### Description**
Fixed the UML Sequence Diagram location issue.
> WPF-973920 Issue in Diagram md file is fixed

- wpf-toc.html
> UG changes for WPF PdfViewer

- wpf-toc.html
- wpf/AI-AssistView/Input-Toolbar.md
Updated the toc file for the input toolbar feature support in the WPF AIAssistView control.
> WPF - 979108 : Updated the toc file for the input toolbar feature support in the WPF AIAssistView control. 

- wpf/Kanban-Board/Getting-started.md
WPF Kanban UG code snippet highlighted.
Dev PR - https://github.com/syncfusion-content/wpf-docs/pull/1919
> 977013-[Hotfix] WPF Kanban UG code snippet highlighted

- wpf/TreeGrid/Filtering.md
Update the UG documentation for behavior changes in FilterLevel extended mode in WPF SfTreeGrid.
**Task link:** [ ES-978602 - Prepare UG documentation for FilterLevel Extended behavior changes in WPF SfTreeGrid](https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/978602)
> ES-978602 - Prepare UG documentation for FilterLevel Extended behavior changes in WPF SfTreeGrid

- wpf/Kanban-Board/Getting-started.md
Update the Header for WPF Kanban Getting started custom model contents.
> 964557- Update the Header for WPF Kanban Getting started custom model contents.
