wpf/RichTextBox/Getting-Started.md
Hi Team,
As the old theme applying code is deprecated, changed the new theme applying code for the SfRichTextBoxAdv control 
Regards,
=> UWP-11284: Added theme applying code for SfRichTextBoxAdv control

wpf/Ribbon/RibbonMerge.md, wpf/SpellChecker/custom-dictionary-support.md
Changed the end tab for the code snippet in RibbonMerge.md and CustomDictionary.md file.
Before Changes:
https://help.syncfusion.com/wpf/spellchecker/custom-dictionary-support?cs-save-lang=1&cs-lang=csharp 
https://help.syncfusion.com/wpf/ribbon/ribbonmerge
=> WPF-839927-XAML code was not updated properly in RibbonMerge

wpf/TreeMap/ToolTip-Support.md
Hi @MuniappanSubramanian sir,
I have updated the code snippet for WPF SfTreeMap tooltip support.
UF link - https://help.syncfusion.com/wpf/treemap/tooltip-support
Regards,
Vishal O.
=> TASK-839896: Correct the inaccurate code snippet to display tooltip in the WPF SfTreeMap control

wpf/RichTextBox/Spell-Check.md
Hi Team,
Updated WPF UG pages with the Spell checking panel option in the below PR
https://github.com/syncfusion-content/wpf-docs/pull/886
From where a space is left between the commands , removed the spaces in this PR
Regards,
=> ES-847658-Update UG pages for spell checking panel option.

wpf/Spreadsheet/Localization.md
Task Link : https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/865353 
**Description :**
I have created a user guide documentation to localize when a resource file is present in a different assembly or namespace.
=> WPF-865353 - How to localize when resource file present in different assembly or default namespace is not same as assembly name

wpf/DataGrid/Data-Binding.md
[ES-861062 Need to add notes for DataBinding page in WPF SfDataGrid](https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/861062).
Regarding this ticket [Can indexed columns be auto-generated in the WPF SfDataGrid control](https://support.syncfusion.com/agent/tickets/529172) I have added the limitation for binding indexer property in WPF SfDataGrid
=> ES-861062 Need to add notes for DataBinding page in WPF SfDataGrid

wpf/Diagram/BPMN-Shapes/BPMN-Activity.md, wpf/Diagram/BPMN-Shapes/BPMN-Connectors.md, wpf/Diagram/BPMN-Shapes/BPMN-Data-Object.md, wpf/Diagram/BPMN-Shapes/BPMN-Data-Store.md, wpf/Diagram/BPMN-Shapes/BPMN-Event.md, wpf/Diagram/BPMN-Shapes/BPMN-Expanded-Sub-Process.md, wpf/Diagram/BPMN-Shapes/BPMN-Gateway.md, wpf/Diagram/BPMN-Shapes/BPMN-Group.md, wpf/Diagram/BPMN-Shapes/BPMN-Shapes.md
Corrected the diagram instance variable name
=> WPF-889895-Corrected the diagram instance variable name

wpf/Diagram/Connector/AppearanceAndValidation.md, wpf/Diagram/Connector/Segments/MultipleSegments.md, wpf/Diagram/Connector/SelectionAndDragging.md
- Corrected the Grammar mistakes
- Changed the style of subtopics to bold
=> WPF-889895-Corrected the Issues

wpf/Diagram/Swimlane/Lane/Interaction.md, wpf/Diagram/Swimlane/Lane/Lane.md, wpf/Diagram/Swimlane/Phase.md, wpf/Diagram/Swimlane/Swimlane-Palette.md, wpf/Diagram/Swimlane/Swimlane.md
- Fixed the display of "Note" section
- Formatted the XAML code
- Added space between the lines
- Highlighted the properties
=> WPF-889895-Corrected the Mistakes

wpf/Breadcrumb/Getting-Started.md, wpf/Button/MVVM.md, wpf/Card-View/Localization.md, wpf/Charts/CodedUI.md, wpf/CheckedListBox/Check-items.md
Hi @gowthamanthavasiyappan,
I have fixed the redirection links, please review.
Regards,
Scholar.
=> SEO-182428-page-with-redirect-links

wpf/Gantt/How-To/Restrict-SelectionMode-as-Single.md
I have updated the Selection mode topic changes.
=> WPF 886828 - Updated Selection mode topic changes

wpf/Pdf-Viewer/Working-with-Annotations/Working-with-Annotations-Programmatically.md
Need to include adding annotation topic under programmatic support
=> 883474 Need to include adding annotation topic under programmatic support

wpf/Pdf-Viewer/Searching-Text.md
Description :
UG update for Find text method in PDFViewer
=> UG update for Find text method in PDFViewer

wpf/Diagram/Page-Settings.md, wpf/Diagram/Printing.md
-- | --
Task Category |Page with Redirect|
Content Task Link/Mail Screenshot | NA|
Hotfix | https://github.com/syncfusion-content/wpf-docs/pull/1497|
Task link | https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/188180/|
Work link | https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B7BC14B52-BBA1-4622-885C-C1BB5D20FB2A%7D&file=Yvone.xlsx&action=default&mobileredirect=true |
Changes Made | Reason for change | Reason for not identifying earlier
-- | -- | --
Page with Redirect| to avoid 304 and redirection links |  
Regards,
Yvone.
=> SEO-1880180 WPF Page with Redirect

wpf/Docking/Pattern-and-Practices.md
Hi @Yvone-Atieno ,
Please review the changes.
-- | --
Task Category | page with redirect|
Content Task Link/Mail Screenshot | |
|Hotfix |https://github.com/syncfusion-content/wpf-docs/pull/1498|
Ticket/Task link |N/A|
|Changes Made | Reason for change |
|-- | -- |
|Changed redirect links | To avoid page redirection issues|  
Regards,
Edith.
=> SEO-187681-page-with-redirect-wpf

wpf-toc.html, wpf/Pdf-Viewer/How-To/Disable-the-Undo-Redo-operation.md
Refer --[UG documentation on disabling the Undo/redo operation in WPF PDFViewer by Yaminisrisf4389 · Pull Request #1528 · syncfusion-content/wpf-docs](https://github.com/syncfusion-content/wpf-docs/pull/1528)
=> UG documentation on disabling the Undo/redo operation in WPF PDFViewer

wpf/Pdf-Viewer/Saving-the-PDF-document.md
Refer -[UG about canceling save in save events by Yaminisrisf4389 · Pull Request #1532 · syncfusion-content/wpf-docs](https://github.com/syncfusion-content/wpf-docs/pull/1532)
=> Update the Ug about canceling save in save events in WPF PdfViewer

wpf/Pdf-Viewer/Working-with-Annotations/Text-Annotation.md
Refer:[UG documentation about changing the Font Family of Free text annotation by Yaminisrisf4389 · Pull Request #1536 · syncfusion-content/wpf-docs](https://github.com/syncfusion-content/wpf-docs/pull/1536)
=> UG documentation about changing the Font Family of Free text annotation

wpf/Maps/Markers.md
Update WPF Maps Example code alignment issue.
=> 925962 - Update WPF Maps Example code alignment issue.

wpf-toc.html, wpf/Pdf-Viewer/How-To/Unload-the-document.md
Description :
Add the UG documentation for need to unload externally, before loading new document
=> 871183-Whether need to unload externally, before loading new document

wpf/Pivot-Grid/How-To/Change-the-Gridline-Color-and-Thickness.md
Description: Add the missing code to apply the BorderThickness for the grid lines in the UG documentation
=> ES-682621 - Add the code to apply the BorderThickness for the grid lines in PivotGrid.

wpf/Diagram/Automatic-Layouts/Automatic-Layouts.md, wpf/Diagram/Automatic-Layouts/RadialTreeLayout.md, wpf/Diagram/Commands/Clipboard.md, wpf/Diagram/Commands/UndoRedo.md, wpf/Diagram/Connector/DefineConnector.md, wpf/Diagram/Connector/SelectionAndDragging.md, wpf/Diagram/Constraints.md, wpf/Diagram/Context-Menu.md, wpf/Diagram/Group.md, wpf/Diagram/Interaction/Dragging/Drag.md, wpf/Diagram/Interaction/Selection.md, wpf/Diagram/Interaction/ZoomPan.md, wpf/Diagram/Node.md, wpf/Diagram/Page-Settings.md, wpf/Diagram/Port/Port.md, wpf/Diagram/Scroll-Settings/ScrollStatusAndAutoScroll.md, wpf/Diagram/Serialization.md, wpf/Diagram/Stencil/Stencil.md, wpf/Diagram/Swimlane/Swimlane.md, wpf/Diagram/UndoRedo.md
Total Number of KB Links = 178.
Total Number of KBs Linked in Phase1 = 78 For more Details Refer[PR Link](https://github.com/syncfusion-content/wpf-docs/pull/1643)
Total Number of KBs Linked in Phase2 = 93.
Total Number of KBs on Doubt = 7.
=> WPF-934460-Link KBs With UG Phase2

wpf/Classic/Chart/How-to/Bind-Data-Using-Data-Context.md, wpf/Release-notes/Migratingtov16.1.0.24.md
-- | --
|Task Category | Site Audit Work- Missing H1|
|Content Task Link/Mail Screenshot |NA|
|Hotfix | https://github.com/syncfusion-content/wpf-docs/pull/1737|
|Ticket/Task link | https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/199937|
|Work link | https://syncfusion.sharepoint.com/:x:/r/sites/GH/_layouts/15/Doc.aspx?sourcedoc=%7B3cf1c3df-fa53-4ea4-8f74-28a05da09714%7D&action=edit&wdinitialsession=e033b7e1-ee0e-17dc-9ccc-7e31c7f249a2&wdrldsc=2&wdrldc=1&wdrldr=ReloadInEditMode%2CTransitionNonMetro%2COnSaveAsWebMet|
Changes Made | Reason for change |
|-- | -- |
| Worked on Missing | In SEO a page should have one H1 title|
|![image](https://github.com/user-attachments/assets/460a03ec-ed1c-41e5-a4c3-f5de6c085023)|Title should contain 70 …
=> SEO-199937--WPF-Classic--Missing-H1

wpf/Menu/Data-Binding.md
Change the code snippet in data binding menuadv UG wpf.
**Menu:**
- Data Binding
=> 964819-Change the code snippet in data binding menuadv UG  wpf

wpf/Kanban-Board/Getting-started.md
WPF Kanban UG document updated regarding custom mapping feature.
=> 977013-[Dev] WPF Kanban UG document updated regarding custom mapping feature 

wpf/Ribbon/DealingWithRibbon.md
Added details about the replacement of ContentTemplate with CaptionTemplate property used for customizing the RibbonTab header.
**Task and Ticket**
Task: https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/979326/
Ticket: https://support.syncfusion.com/agent/tickets/709759
Regards,
Sekar Sivalingam
=> WPF-979326 : Enhance RibbonTab Header Customization Documentation with Code Example and UI Screenshot
